import type { VisualModuleDefinition } from '../types';
import { createAudioMapper, createLiveMapper } from '../mapping';

export const videoFlowModule: VisualModuleDefinition = {
  id: 'Video Flow',
  label: 'Video Flow',
  liveLabel: 'Flow',
  presetId: 'Video Flow',
  description: 'No-text neon ribbons and liquid tunnel motion',
  renderMode: 'webgl-2d',
  defaultLook: {
    currentScene: 'Video Flow',
    baseColor: '#00d8ff',
    secondaryColor: '#5a29ff',
    accentColor: '#d46cff',
    bgColor: '#010208',
    bloomIntensity: 1.12,
    bloomThreshold: 0.5,
    rgbSplitAmount: 0.003,
    distortion: 0.14,
    glitchActive: false,
    speed: 0.92,
    chaos: 0.58,
    contrast: 1.08,
    saturation: 1.34,
    brightness: 1.08,
    textInput: '',
    musicCameraEnabled: false,
    audioFxReactive: true,
  },
  mapAudioToVisualState: createAudioMapper({
    beat: 0.92,
    bass: 0.92,
    mid: 1.0,
    treble: 1.0,
    transient: 0.82,
    fx: 0.98,
    experimental: 1.0,
  }),
  mapLiveControlsToParams: createLiveMapper({
    motion: 1.26,
    impact: 0.88,
    warmth: 0.78,
    saturation: 1.42,
    brightness: 0.62,
    detail: 1.5,
    variation: 1.44,
    structureScale: 1.5,
    structureWarp: 1.8,
    atmosphereGlow: 1.42,
    atmosphereDepth: 1.5,
    bloomBoost: 0.2,
    rgbSplitBoost: 0.02,
    distortionBoost: 0.32,
  }),
};
